var user = {
"login": "mgriffeth",
"id": 8284438,
"avatar_url": "https://avatars.githubusercontent.com/u/8284438?v=2",
"gravatar_id": "",
"url": "https://api.github.com/users/mgriffeth",
"html_url": "https://github.com/mgriffeth",
"followers_url": "https://api.github.com/users/mgriffeth/followers",
"following_url": "https://api.github.com/users/mgriffeth/following{/other_user}",
"gists_url": "https://api.github.com/users/mgriffeth/gists{/gist_id}",
"starred_url": "https://api.github.com/users/mgriffeth/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/mgriffeth/subscriptions",
"organizations_url": "https://api.github.com/users/mgriffeth/orgs",
"repos_url": "https://api.github.com/users/mgriffeth/repos",
"events_url": "https://api.github.com/users/mgriffeth/events{/privacy}",
"received_events_url": "https://api.github.com/users/mgriffeth/received_events",
"type": "User",
"site_admin": false,
"name": "Matthew Griffeth",
"company": "",
"blog": "",
"location": "",
"email": "",
"hireable": false,
"bio": null,
"public_repos": 7,
"public_gists": 0,
"followers": 0,
"following": 0,
"created_at": "2014-07-27T23:37:59Z",
"updated_at": "2014-10-08T17:06:16Z"
}
